[rust] Fix `Cargo.lock` and add presubmit for `cargo --offline --locked`
After https://crrev.com/c/7697798 `gnrt gen` started failing (maybe
because `git` conflict resolution/rebasing isn't always sufficient for
updating `Cargo.lock`?):

```
$ tools/crates/run_gnrt.py gen
    Finished `release` profile [optimized] target(s) in 0.16s
     Running `out/gnrt/target/release/gnrt gen`
Generating GN rules from `third_party/rust/chromium_crates_io/Cargo.toml` ...
Error: running cargo metadata

Caused by:
    0: `cargo metadata` execution failed
    1: `cargo metadata` exited with an error: error: cannot update the lock file /usr/local/google/home/lukasza/src/chromium3/src/third_party/rust/chromium_crates_io/Cargo.lock because --locked was passed to prevent this
       help: to generate the lock file without accessing the network, remove the --locked flag and use --offline instead.
```

This CL:

* Fixes `Cargo.lock`
    - The fix was generated by just running `gnrt vendor`
    - This avoids the `gnrt gen` error above
* Adds a presubmit that runs (roughly)
  `cargo metadata --offline --locked` under
  `third_party/rust/chromium_crates_io`.
  The presubmit should be capable of detecting:

    - `Cargo.lock` malformed or out-of-date
    - Old crates in `vendor/` directory

The presubmit above is hermetic and only depends on things in the
Chromium repo (unlike `tools/crates/run_gnrt.py gen` which depends on
crates.io for building `gnrt`).

Bug: None
Change-Id: I63f3a483a83ab6eaac6931a264a42f88c0ac6d6a
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/7854258
Auto-Submit: Łukasz Anforowicz <lukasza@chromium.org>
Reviewed-by: Liza Burakova <liza@chromium.org>
Commit-Queue: Łukasz Anforowicz <lukasza@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1632978}
NOKEYCHECK=True
GitOrigin-RevId: d685f19868ba58f49a4028bbed702aa09c909551